# name must be autofix.ci for security reasons
# ref: https://autofix.ci/security
name: autofix.ci

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read # for checkout

    steps:
      - name: Install mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2025.7.27
          sha256: fe734fda24998331886ecc7331f157268dcefbdb16fb8489a1181dde5c9f29f3
