name: autofix.ci

on: []

permissions: {}

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read # for checkout

    steps:
      - name: Install mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: v2025.8.1
          sha256: 76e3c9d9c790290f8a3fbcfd93adae95f32da7ecd52706ba91f6252a40dbcb31
